name: Deploy CCI Actions Demo
on:
  push:
    branches:
       master
env:
  REGION_ID: cn-north-4                  # set this to your preferred huaweicloud region, e.g. cn-north-4
  PROJECT_ID: 086cd4ee9e00268e2f76c00ea33b6cbe   # 项目ID，可以在华为云我的凭证获取
  ACCESS_KEY_ID: ${{ secrets.ACCESSKEY }}             # set this to your huaweicloud access-key-id
  ACCESS_KEY_SECRET: ${{ secrets.SECRETACCESSKEY }}               # set this to your huaweicloud access-key-secret
  SWR_ORGANIZATION: swr-lizy2   # SWR 组织名
  IMAGE_NAME: tomcat       # 镜像名称
            
jobs:
  deploy_cci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build with Maven
        id: build-project
        run: mvn package -Dmaven.test.skip=true -U -e -X -B
        
      - name: Log in to HuaweiCloud SWR
        uses: huaweicloud/swr-login@v1
        with:
          region: ${{ env.REGION_ID }}
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}

      - name: Build, tag, and push image to HuaweiCloud SWR
        id: build-image
        env:
          SWR_REGISTRY: swr.${{ env.REGION_ID }}.myhuaweicloud.com
          SWR_ORGANIZATION: ${{ env.SWR_ORGANIZATION }}
          IMAGE_TAG: maven-samp-3cf451e
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          docker build -t $SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG .
          docker push $SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG
          echo "::set-output name=image::$SWR_REGISTRY/$SWR_ORGANIZATION/$IMAGE_NAME:$IMAGE_TAG"
          
      - name: Kubectl tool installer
        id: install-kubectl
        uses: Azure/setup-kubectl@v2.1

      # 通过镜像新建或者更新负载
      - name: deploy to cci
        uses: huaweicloud/deploy-cci-action@v1.0.1
        id: deploy-to-cci
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          project_id: ${{env.PROJECT_ID}}
          region: ${{ env.REGION_ID }}
          namespace: action-namespace-name
          deployment: action-deployment-name
          image: ${{ steps.build-image.outputs.image }}


      # 通过yaml新建或者更新负载,yaml文件可以根据自己的需求修改pod数量，容器的端口，cpu, 内存
      # - name: deploy to cci
      #   uses: huaweicloud/deploy-cci-action@v1.0.1
      #   id: deploy-to-cci
      #   with:
      #     access_key: ${{ secrets.ACCESSKEY }}
      #     secret_key: ${{ secrets.SECRETACCESSKEY }}
      #     project_id: ${{env.PROJECT_ID}}
      #     region: ${{ env.REGION_ID }}
      #     namespace: action-namespace-name
      #     deployment: action-deployment-name
      #     manifest: './deployment.yaml' 
      #     image: ${{ steps.build-image.outputs.image }}